[2024-08-11T04:41:37.161+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:41:37.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:41:37.176+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:41:37.176+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:41:50.150+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:41:50.908+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:41:50.977+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:41:51.330+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:41:51.330+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:41:51.371+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:41:51.371+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:41:51.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 14.273 seconds
[2024-08-11T04:42:21.470+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:42:21.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:42:21.476+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:42:21.474+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:42:32.328+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:42:32.989+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:42:32.999+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:42:33.024+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:42:33.024+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:42:33.041+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:42:33.040+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:42:33.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.599 seconds
[2024-08-11T04:43:03.649+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:43:03.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:43:03.692+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:43:03.691+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:43:12.051+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:43:12.560+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:43:12.565+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:43:12.584+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:43:12.584+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:43:12.601+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:43:12.600+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:43:12.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.997 seconds
[2024-08-11T04:43:42.801+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:43:42.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:43:42.823+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:43:42.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:44:12.817+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:44:12.817+0000] {timeout.py:68} ERROR - Process timed out, PID: 84
[2024-08-11T04:44:43.029+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:44:43.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:44:43.031+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:44:43.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:44:50.539+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:44:51.253+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:44:51.261+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:44:51.398+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:44:51.398+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:44:51.413+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:44:51.413+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:44:51.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.409 seconds
[2024-08-11T04:45:21.560+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:45:21.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:45:21.561+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:45:21.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:45:28.805+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:45:29.289+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:45:29.294+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:45:29.320+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:45:29.320+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:45:29.337+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:45:29.337+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:45:29.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.797 seconds
[2024-08-11T04:45:59.511+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:45:59.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:45:59.515+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:45:59.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:46:09.385+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:46:10.051+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:46:10.060+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:46:10.085+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:46:10.084+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:46:10.104+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:46:10.103+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:46:10.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 10.618 seconds
[2024-08-11T04:46:40.396+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:46:40.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:46:40.398+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:46:40.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:46:49.234+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:46:49.707+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:46:49.715+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:46:49.739+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:46:49.739+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:46:49.756+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:46:49.756+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:46:49.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.380 seconds
[2024-08-11T04:47:19.906+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:47:19.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:47:19.908+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:47:19.907+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:47:28.417+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:47:28.934+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:47:28.940+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:47:28.966+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:47:28.965+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:47:28.984+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:47:28.984+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:47:29.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.104 seconds
[2024-08-11T04:47:59.052+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:47:59.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:47:59.054+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:47:59.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:48:09.843+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:48:10.318+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:48:10.323+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:48:10.342+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:48:10.342+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:48:10.357+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:48:10.357+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:48:10.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.325 seconds
[2024-08-11T04:48:40.502+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:48:40.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:48:40.504+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:48:40.503+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:48:48.750+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:48:49.213+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:48:49.218+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:48:49.238+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:48:49.238+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:48:49.260+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:48:49.260+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:48:49.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.781 seconds
[2024-08-11T04:49:19.419+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:49:19.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:49:19.421+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:49:19.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:49:27.165+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:49:27.770+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:49:27.779+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:49:27.810+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:49:27.810+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:49:27.833+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:49:27.832+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:49:27.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.435 seconds
[2024-08-11T04:49:58.003+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:49:58.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:49:58.005+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:49:58.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:50:05.633+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:50:06.174+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:50:06.183+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:50:06.210+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:50:06.209+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:50:06.229+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:50:06.228+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:50:06.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.247 seconds
[2024-08-11T04:50:36.362+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:50:36.363+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:50:36.364+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:50:36.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:50:46.951+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:50:47.401+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:50:47.406+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:50:47.425+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:50:47.425+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:50:47.470+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:50:47.470+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:50:47.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.126 seconds
[2024-08-11T04:51:17.602+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:51:17.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:51:17.603+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:51:17.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:51:25.129+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:51:25.586+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:51:25.592+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:51:25.612+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:51:25.612+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:51:25.629+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:51:25.629+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:51:25.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.046 seconds
[2024-08-11T04:51:55.768+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:51:55.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:51:55.770+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:51:55.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:52:03.059+0000] {logging_mixin.py:188} INFO - Successfully saved 1000 articles to ai_news_articles.json and ai_news_articles.csv
[2024-08-11T04:52:03.501+0000] {logging_mixin.py:188} INFO - Successfully loaded data into news_articles table
[2024-08-11T04:52:03.509+0000] {processor.py:840} INFO - DAG(s) 'etl_data_pipeline' retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:52:03.532+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:52:03.532+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-08-11T04:52:03.549+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:52:03.548+0000] {dag.py:3954} INFO - Setting next_dagrun for etl_data_pipeline to 2024-08-10 00:00:00+00:00, run_after=2024-08-11 00:00:00+00:00
[2024-08-11T04:52:03.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.801 seconds
[2024-08-11T04:52:33.708+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:52:33.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:52:33.710+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:52:33.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:52:45.063+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:52:45.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:52:45.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:52:45.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.443 seconds
[2024-08-11T04:53:15.263+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:53:15.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:53:15.265+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:53:15.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:53:22.140+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:53:22.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:53:22.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:53:22.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.905 seconds
[2024-08-11T04:53:52.233+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:53:52.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:53:52.236+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:53:52.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:53:59.063+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:53:59.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:53:59.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:53:59.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.861 seconds
[2024-08-11T04:54:29.239+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:54:29.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:54:29.241+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:54:29.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:54:35.778+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:54:35.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:54:35.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:54:35.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.570 seconds
[2024-08-11T04:55:06.253+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:55:06.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:55:06.255+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:55:06.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:55:36.272+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:55:36.272+0000] {timeout.py:68} ERROR - Process timed out, PID: 254
[2024-08-11T04:56:06.439+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:56:06.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:56:06.440+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:56:06.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:56:15.771+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:56:15.765+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:56:15.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:56:15.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.355 seconds
[2024-08-11T04:56:45.941+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:56:45.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:56:45.942+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:56:45.942+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:57:15.948+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:57:15.947+0000] {timeout.py:68} ERROR - Process timed out, PID: 282
[2024-08-11T04:57:46.098+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:57:46.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:57:46.100+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:57:46.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:57:55.921+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:57:55.914+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:57:55.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:57:55.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.845 seconds
[2024-08-11T04:58:26.048+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:58:26.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:58:26.050+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:58:26.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:58:36.350+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:58:36.346+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:58:36.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:58:36.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 10.323 seconds
[2024-08-11T04:59:06.494+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:59:06.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:59:06.495+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:59:06.495+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:59:16.011+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:59:16.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:59:16.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:59:16.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.537 seconds
[2024-08-11T04:59:46.168+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T04:59:46.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T04:59:46.169+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:59:46.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:59:52.955+0000] {logging_mixin.py:188} INFO - [2024-08-11T04:59:52.949+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T04:59:52.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T04:59:52.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.825 seconds
[2024-08-11T05:00:23.537+0000] {processor.py:161} INFO - Started process (PID=335) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:00:23.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:00:23.552+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:00:23.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:00:30.215+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:00:30.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:00:30.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:00:30.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.804 seconds
[2024-08-11T05:01:01.158+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:01:01.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:01:01.160+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:01:01.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:01:08.861+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:01:08.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:01:08.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:01:08.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.785 seconds
[2024-08-11T05:01:39.336+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:01:39.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:01:39.338+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:01:39.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:01:47.193+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:01:47.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:01:47.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:01:47.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.898 seconds
[2024-08-11T05:02:17.371+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:02:17.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:02:17.373+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:02:17.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:02:37.205+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:02:37.198+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:02:37.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:02:37.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 19.856 seconds
[2024-08-11T05:03:07.361+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:03:07.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:03:07.363+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:03:07.363+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:03:16.430+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:03:16.426+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:03:16.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:03:16.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.090 seconds
[2024-08-11T05:03:46.515+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:03:46.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:03:46.517+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:03:46.517+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:03:57.391+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:03:57.384+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:03:57.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:03:57.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 10.918 seconds
[2024-08-11T05:04:27.579+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:04:27.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:04:27.581+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:04:27.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:04:34.768+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:04:34.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:04:34.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:04:34.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.256 seconds
[2024-08-11T05:05:04.977+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:05:04.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:05:04.979+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:05:04.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:05:13.428+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:05:13.422+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:05:13.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:05:13.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.470 seconds
[2024-08-11T05:05:43.579+0000] {processor.py:161} INFO - Started process (PID=412) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:05:43.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:05:43.581+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:05:43.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:06:13.585+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:06:13.585+0000] {timeout.py:68} ERROR - Process timed out, PID: 412
[2024-08-11T05:06:43.730+0000] {processor.py:161} INFO - Started process (PID=426) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:06:43.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:06:43.732+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:06:43.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:06:54.558+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:06:54.552+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:06:54.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:06:54.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 10.853 seconds
[2024-08-11T05:07:24.696+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:07:24.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:07:24.698+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:07:24.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:07:36.572+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:07:36.568+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:07:36.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:07:36.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.944 seconds
[2024-08-11T05:08:06.751+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:08:06.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:08:06.752+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:08:06.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:08:20.145+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:08:20.139+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:08:20.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:08:20.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 13.415 seconds
[2024-08-11T05:08:50.297+0000] {processor.py:161} INFO - Started process (PID=462) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:08:50.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:08:50.299+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:08:50.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:09:06.713+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:09:06.706+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:09:06.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:09:06.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 16.439 seconds
[2024-08-11T05:09:36.867+0000] {processor.py:161} INFO - Started process (PID=470) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:09:36.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:09:36.870+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:09:36.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:09:43.885+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:09:43.879+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:09:43.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:09:43.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.042 seconds
[2024-08-11T05:10:14.010+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:10:14.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:10:14.012+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:10:14.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:10:33.659+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:10:33.653+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:10:33.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:10:33.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 19.672 seconds
[2024-08-11T05:11:03.819+0000] {processor.py:161} INFO - Started process (PID=491) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:11:03.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:11:03.820+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:11:03.820+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:11:11.891+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:11:11.884+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:11:11.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:11:11.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.161 seconds
[2024-08-11T05:11:42.053+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:11:42.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:11:42.054+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:11:42.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:11:50.920+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:11:50.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:11:50.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:11:50.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 8.891 seconds
[2024-08-11T05:12:21.094+0000] {processor.py:161} INFO - Started process (PID=514) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:12:21.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:12:21.097+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:12:21.096+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:12:40.065+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:12:40.057+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:12:40.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:12:40.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 19.019 seconds
[2024-08-11T05:13:10.147+0000] {processor.py:161} INFO - Started process (PID=523) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:13:10.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:13:10.150+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:13:10.149+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:13:20.430+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:13:20.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:13:20.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:13:20.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 10.305 seconds
[2024-08-11T05:13:50.612+0000] {processor.py:161} INFO - Started process (PID=537) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:13:50.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:13:50.614+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:13:50.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:14:05.048+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:14:05.041+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:14:05.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:14:05.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 14.460 seconds
[2024-08-11T05:14:35.204+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:14:35.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:14:35.206+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:14:35.206+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:14:42.798+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:14:42.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:14:42.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:14:42.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.628 seconds
[2024-08-11T05:15:13.144+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:15:13.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:15:13.146+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:15:13.145+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:15:23.038+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:15:23.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:15:23.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:15:23.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.951 seconds
[2024-08-11T05:15:53.230+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:15:53.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:15:53.232+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:15:53.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:16:23.528+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:16:23.500+0000] {timeout.py:68} ERROR - Process timed out, PID: 568
[2024-08-11T05:16:57.544+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:16:57.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:16:57.546+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:16:57.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:17:27.747+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:17:27.722+0000] {timeout.py:68} ERROR - Process timed out, PID: 576
[2024-08-11T05:17:59.943+0000] {processor.py:161} INFO - Started process (PID=578) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:17:59.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:17:59.946+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:17:59.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:18:40.372+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:18:40.103+0000] {timeout.py:68} ERROR - Process timed out, PID: 578
[2024-08-11T05:19:12.763+0000] {processor.py:161} INFO - Started process (PID=591) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:19:12.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:19:12.766+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:19:12.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:19:19.750+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:19:19.742+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:19:19.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:19:19.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.026 seconds
[2024-08-11T05:19:50.000+0000] {processor.py:161} INFO - Started process (PID=605) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:19:50.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:19:50.002+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:19:50.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:20:01.494+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:20:01.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:20:01.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:20:01.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.533 seconds
[2024-08-11T05:20:31.683+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:20:31.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:20:31.686+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:20:31.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:20:40.894+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:20:40.882+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:20:40.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:20:40.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.240 seconds
[2024-08-11T05:21:11.039+0000] {processor.py:161} INFO - Started process (PID=621) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:21:11.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:21:11.043+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:21:11.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:21:17.830+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:21:17.824+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:21:17.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:21:17.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.812 seconds
[2024-08-11T05:21:48.029+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:21:48.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:21:48.031+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:21:48.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:22:02.020+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:22:02.012+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:22:02.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:22:02.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 14.032 seconds
[2024-08-11T05:22:32.216+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:22:32.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:22:32.218+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:22:32.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:22:39.201+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:22:39.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:22:39.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:22:39.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.018 seconds
[2024-08-11T05:23:09.387+0000] {processor.py:161} INFO - Started process (PID=652) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:23:09.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:23:09.389+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:23:09.389+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:23:16.216+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:23:16.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:23:16.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:23:16.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.853 seconds
[2024-08-11T05:23:46.387+0000] {processor.py:161} INFO - Started process (PID=666) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:23:46.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:23:46.389+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:23:46.389+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:23:53.474+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:23:53.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:23:53.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:23:53.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.161 seconds
[2024-08-11T05:24:23.654+0000] {processor.py:161} INFO - Started process (PID=674) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:24:23.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:24:23.656+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:24:23.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:24:30.552+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:24:30.546+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:24:30.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:24:30.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 6.930 seconds
[2024-08-11T05:25:00.739+0000] {processor.py:161} INFO - Started process (PID=682) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:25:00.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:25:00.741+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:25:00.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:25:12.388+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:25:12.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:25:12.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:25:12.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.688 seconds
[2024-08-11T05:25:42.570+0000] {processor.py:161} INFO - Started process (PID=690) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:25:42.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:25:42.572+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:25:42.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:25:50.350+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:25:50.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:25:50.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:25:50.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.809 seconds
[2024-08-11T05:26:20.514+0000] {processor.py:161} INFO - Started process (PID=704) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:26:20.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:26:20.516+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:26:20.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:26:27.642+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:26:27.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:26:27.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:26:27.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.264 seconds
[2024-08-11T05:26:57.899+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:26:57.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:26:57.901+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:26:57.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:27:08.367+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:27:08.359+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:27:08.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:27:08.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 10.500 seconds
[2024-08-11T05:27:38.645+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:27:38.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:27:38.647+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:27:38.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:27:45.856+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:27:45.847+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:27:45.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:27:45.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.261 seconds
[2024-08-11T05:28:16.033+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:28:16.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:28:16.035+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:28:16.035+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:28:46.040+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:28:46.040+0000] {timeout.py:68} ERROR - Process timed out, PID: 728
[2024-08-11T05:29:16.190+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:29:16.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:29:16.192+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:29:16.192+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:29:27.193+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:29:27.185+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:29:27.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:29:27.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 11.034 seconds
[2024-08-11T05:29:57.361+0000] {processor.py:161} INFO - Started process (PID=755) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:29:57.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:29:57.362+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:29:57.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:30:11.525+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:30:11.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:30:11.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:30:11.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 14.212 seconds
[2024-08-11T05:30:41.695+0000] {processor.py:161} INFO - Started process (PID=763) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:30:41.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:30:41.698+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:30:41.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:30:51.499+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:30:51.489+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:30:51.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:30:51.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 9.856 seconds
[2024-08-11T05:31:21.699+0000] {processor.py:161} INFO - Started process (PID=778) to work on /opt/airflow/dags/newspipeline.py
[2024-08-11T05:31:21.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/newspipeline.py for tasks to queue
[2024-08-11T05:31:21.701+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:31:21.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:31:28.704+0000] {logging_mixin.py:188} INFO - [2024-08-11T05:31:28.698+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/newspipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/newspipeline.py", line 101, in <module>
    df = extract_data()
         ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newspipeline.py", line 34, in extract_data
    for article in query.execQuery(er, sortBy="date", maxItems=1000):
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
    self._getNextArticleBatch()
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
    res = self._er.execQuery(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
    respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
    raise self._lastException or Exception("No valid return data provided")
  File "/home/airflow/.local/lib/python3.12/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
    raise Exception(respInfo.text)
Exception: You have used all available tokens for unsubscribed users. In order to continue using Event Registry please subscribe to a paid plan.
[2024-08-11T05:31:28.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/newspipeline.py
[2024-08-11T05:31:28.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/newspipeline.py took 7.041 seconds
